In [32]:
import numpy as np
import pandas as pd

from decimal import *
getcontext().prec = 100

In [33]:
xi = None
yi = None

global h1
h1 = 0.25

decimal_places = '0.000001'

x_range = 5

In [34]:
def given_func(x, y):
    x = Decimal(str(x)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)
    y = Decimal(str(y)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)
    
    main_func = Decimal('-2')*(x**3) + Decimal('12')*(x**2) - Decimal('20')*x + Decimal('8.5')
    
    return Decimal(str(main_func)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)


def method_func(xi, yi, h=h1):
    xi = Decimal(str(xi)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)
    yi = Decimal(str(yi)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)
    h = Decimal(str(h)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)
    
    return Decimal(str(yi + (given_func(xi, yi))*h)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)

In [35]:
# appending x values to array
list_x = []
i = 0
while i <= x_range:
    list_x.append(i)
    i+=h1


data_arr = np.zeros((len(list_x), 1), dtype=np.float64)
data_arr[:,0] = np.transpose(list_x)

In [36]:
# making y values
list_y = [1]

In [37]:
for i in range(len(list_x) - 1):
    
    yi = method_func(list_x[i], list_y[i])
    
    list_y.append(yi)


data_arr = np.append(data_arr, np.transpose([list_y]), axis=1)

In [38]:
df = pd.DataFrame(data_arr, columns=['x', 'y'])
df

       x           y
0    0.0           1
1   0.25    3.125000
2    0.5    4.179688
3   0.75    4.492188
4    1.0    4.343751
5   1.25    3.968751
6    1.5    3.554689
7   1.75    3.242189
8    2.0    3.125002
9   2.25    3.250002
10   2.5    3.617190
11  2.75    4.179690
12   3.0    4.843753
13  3.25    5.468753
14   3.5    5.867191
15  3.75    5.804691
16   4.0    5.000004
17  4.25    3.125004
18   4.5   -0.195309
19  4.75   -5.382809
20   5.0  -12.906247