In [1]:
import numpy as np
import pandas as pd

from decimal import *
getcontext().prec = 100

In [2]:
xi = None
yi = None
k1 = None
k2 = None

global h1
h1 = 0.25

decimal_places = '0.000001'

x_range = 5

In [3]:
def given_func(x, y):
    x = Decimal(str(x)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)
    y = Decimal(str(y)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)
    
    main_func = Decimal('-2')*(x**3) + Decimal('12')*(x**2) - Decimal('20')*x + Decimal('8.5')
    
    return Decimal(str(main_func)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)


def method_func(xi, yi, k1, k2, h=h1):
    xi = Decimal(str(xi)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)
    yi = Decimal(str(yi)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)
    k1 = Decimal(str(k1)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)
    k2 = Decimal(str(k2)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)
    h = Decimal(str(h)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)
    
    return Decimal(str(yi + k2*h)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)

def return_k1(xi, yi):
    return given_func(xi, yi)

def return_k2(xi, yi, k1, h=h1): 
    xi = Decimal(str(xi)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)
    yi = Decimal(str(yi)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)
    k1 = Decimal(str(k1)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)
    h = Decimal(str(h)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)
    
    x = xi +(Decimal('0.5')*h)
    y = yi + (Decimal('0.5')*k1*h)
    
    return given_func(x, y)

In [4]:
# appending x values to array
list_x = []
i = 0
while i <= x_range:
    list_x.append(i)
    i+=h1


data_arr = np.zeros((len(list_x), 1), dtype=np.float64)
data_arr[:,0] = np.transpose(list_x)

In [5]:
# making y values
list_y = [1]
list_k1 = [0]
list_k2 = [0]

In [6]:
for i in range(len(list_x) - 1):
    k1 = return_k1(list_x[i], list_y[i])
    k2 = return_k2(list_x[i], list_y[i], k1)
    
    yi = method_func(list_x[i], list_y[i], k1, k2)
    
    list_y.append(yi)
    list_k1.append(k1)
    list_k2.append(k2)


data_arr = np.append(data_arr, np.transpose([list_y]), axis=1)
data_arr = np.append(data_arr, np.transpose([list_k1]), axis=1)
data_arr = np.append(data_arr, np.transpose([list_k2]), axis=1)

In [7]:
df = pd.DataFrame(data_arr, columns=['x', 'y', 'k1', 'k2'])
df

       x           y          k1          k2
0    0.0           1           0           0
1   0.25    2.545899    8.500000    6.183594
2    0.5    3.191407    4.218750    2.582031
3   0.75    3.241212    1.250000    0.199219
4    1.0    2.953126   -0.593750   -1.152344
5   1.25    2.538087   -1.500000   -1.660156
6    1.5    2.160157   -1.656250   -1.511719
7   1.75    1.936524   -1.250000   -0.894531
8    2.0    1.937501   -0.468750    0.003906
9   2.25    2.186525    0.500000    0.996094
10   2.5    2.660158    1.468750    1.894531
11  2.75    3.288088    2.250000    2.511719
12   3.0    3.953127    2.656250    2.660156
13  3.25    4.491213    2.500000    2.152344
14   3.5    4.691408    1.593750    0.800781
15  3.75    4.295900   -0.250000   -1.582031
16   4.0    3.000002   -3.218750   -5.183594
17  4.25    0.452151   -7.500000  -10.191406
18   4.5   -3.746091  -13.281250  -16.792969
19  4.75  -10.040036  -20.750000  -25.175781
20   5.0  -18.921872  -30.093750  -35.527344