In [1]:
import numpy as np
import pandas as pd

from decimal import *
getcontext().prec = 100

In [2]:
xi = None
yi = None
k1 = None
k2 = None

global h1
h1 = 0.25

decimal_places = '0.000001'

x_range = 5

In [3]:
def given_func(x, y):
    x = Decimal(str(x)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)
    y = Decimal(str(y)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)
    
    main_func = Decimal('-2')*(x**3) + Decimal('12')*(x**2) - Decimal('20')*x + Decimal('8.5')
    
    return Decimal(str(main_func)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)


def method_func(xi, yi, k1, k2, h=h1):
    xi = Decimal(str(xi)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)
    yi = Decimal(str(yi)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)
    k1 = Decimal(str(k1)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)
    k2 = Decimal(str(k2)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)
    h = Decimal(str(h)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)
    
    return Decimal(str(yi + ((Decimal(1/3)*k1) + (Decimal(2/3)*k2))*h)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)

def return_k1(xi, yi):
    return given_func(xi, yi)

def return_k2(xi, yi, k1, h=h1): 
    xi = Decimal(str(xi)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)
    yi = Decimal(str(yi)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)
    k1 = Decimal(str(k1)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)
    h = Decimal(str(h)).quantize(Decimal(decimal_places), rounding=ROUND_HALF_UP)
    
    x = xi +(Decimal('0.75')*h)
    y = yi + (Decimal('0.75')*k1*h)
    
    return given_func(x, y)

In [4]:
# appending x values to array
list_x = []
i = 0
while i <= x_range:
    list_x.append(i)
    i+=h1


data_arr = np.zeros((len(list_x), 1), dtype=np.float64)
data_arr[:,0] = np.transpose(list_x)

In [5]:
# making y values
list_y = [1]
list_k1 = [0]
list_k2 = [0]

In [6]:
for i in range(len(list_x) - 1):
    k1 = return_k1(list_x[i], list_y[i])
    k2 = return_k2(list_x[i], list_y[i], k1)
    
    yi = method_func(list_x[i], list_y[i], k1, k2)
    
    list_y.append(yi)
    list_k1.append(k1)
    list_k2.append(k2)


data_arr = np.append(data_arr, np.transpose([list_y]), axis=1)
data_arr = np.append(data_arr, np.transpose([list_k1]), axis=1)
data_arr = np.append(data_arr, np.transpose([list_k2]), axis=1)

In [7]:
df = pd.DataFrame(data_arr, columns=['x', 'y', 'k1', 'k2'])
df

       x           y          k1          k2
0    0.0           1           0           0
1   0.25    2.568115    8.500000    5.158691
2    0.5    3.232910    4.218750    1.879395
3   0.75    3.299072    1.250000   -0.228027
4    1.0    3.024414   -0.593750   -1.351074
5   1.25    2.619873   -1.500000   -1.677246
6    1.5    2.249512   -1.656250   -1.394043
7   1.75    2.030518   -1.250000   -0.688965
8    2.0    2.033203   -0.468750    0.250488
9   2.25    2.281006    0.500000    1.236816
10   2.5    2.750488    1.468750    2.082520
11  2.75    3.371338    2.250000    2.600098
12   3.0    4.026367    2.656250    2.602051
13  3.25    4.551513    2.500000    1.900879
14   3.5    4.735839    1.593750    0.309082
15  3.75    4.321532   -0.250000   -2.360840
16   4.0    3.003905   -3.218750   -6.296387
17  4.25    0.431395   -7.500000  -11.685059
18   4.5   -3.794435  -13.281250  -18.714355
19  4.75  -10.118898  -20.750000  -27.571777
20   5.0  -19.034181  -30.093750  -38.444824